repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9005
    hooks:
      - id: parsable-R
      - id: no-browser-statement
      - id: no-print-statement
      - id: no-debug-statement
      - id: deps-in-desc
        args: [--root=r/]
        exclude: 'do.R'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
        args: [ --assume-in-merge ]
      - id: check-added-large-files
        args: ['--maxkb=200']
      - id: file-contents-sorter
        files: '\.Rbuildignore$'
      - id: end-of-file-fixer
        exclude: '(\.Rd|python/doc/source/reference/.*|test-doctest-.*)'

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.5.0"
    hooks:
      - id: tox-ini-fmt
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.5.1"
    hooks:
      - id: pyproject-fmt
        additional_dependencies: ["tox>=4.12.1"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.0
    hooks:
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
      # Run the linter.
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        types_or: [ python, pyi, jupyter ]
        require_serial: true
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.0
    hooks:
      - id: sphinx-lint
