[tox]
min_version = 4.0
env_list = py{38,39,310,311}

[testenv]
description = run unit tests
install_command =
    pip install --find-links wheelhouse moocore
deps =
    pytest>=7
commands =
    pytest --doctest-modules --ignore-glob="*generate-expected-output.py"
    
[testenv:coverage]
description = run coverage
deps =
    pytest>=7
    pytest-cov
commands =
    pytest --cov --cov-report=xml

[testenv:docs]
description = Build documentation
extras =
    doc
deps = -r{toxinidir}/requirements_dev.txt
# commands =
#          sphinx-apidoc --module-first --no-toc -f -o doc/api/ ./src/ '_*.py' '**conftest.py'

[testenv:type]
deps = mypy
commands = mypy sr

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
